FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements-dev.txt /app/requirements-dev.txt
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements-dev.txt

COPY app /app/app
COPY tests /app/tests

CMD ["pytest", "-q"]

