-- 02_seed.sql
-- Seed the source database entirely server-side.
--
-- Every row is generated by generate_series inside the instance, so no data crosses the
-- network. Seeding 12M orders from a laptop with a client-side INSERT loop would be
-- bounded by conference wifi; this is bounded by the instance's disk.
--
-- The row counts are psql variables so a run can be tuned to the time available. Each is
-- set only if it was not already supplied on the command line, so an override needs no
-- edit to this file:
--
--   psql -h "$PGHOST" -U postgres -d shop -v orders=2000000 -f 02_seed.sql
--
-- The defaults are sized for the RDS instance created by ../terraform. They are far too
-- large to run against a laptop container -- pass smaller values if you are testing.
\if :{?customers}
\else
  \set customers 500000
\endif
\if :{?products}
\else
  \set products 20000
\endif
\if :{?orders}
\else
  \set orders 12000000
\endif
\if :{?items_per_order}
\else
  \set items_per_order 4
\endif

\echo 'Seeding customers=':customers' products=':products' orders=':orders' items_per_order=':items_per_order

INSERT INTO customers (email, region, created_at)
SELECT 'c' || g || '@example.test',
       (ARRAY['us-east','us-west','eu-west','apac'])[1 + (g % 4)],
       now() - (random() * interval '365 days')
FROM generate_series(1, :customers) g;

INSERT INTO products (sku, category, unit_price)
SELECT 'SKU-' || lpad(g::text, 7, '0'),
       (ARRAY['audio','video','home','outdoor','kitchen'])[1 + (g % 5)],
       round((random() * 400 + 5)::numeric, 2)
FROM generate_series(1, :products) g;

INSERT INTO orders (customer_id, status, placed_at, updated_at)
SELECT 1 + (random() * (:customers - 1))::bigint,
       (ARRAY['placed','paid','shipped','refunded'])[1 + (g % 4)],
       now() - (random() * interval '90 days'),
       now()
FROM generate_series(1, :orders) g;

-- One row per (order, item slot). order_items.placed_at is copied from the order so the
-- benchmark queries in ../bench can filter either table on the same time window.
INSERT INTO order_items (order_id, product_id, quantity, line_total, placed_at)
SELECT o.order_id,
       1 + (random() * (:products - 1))::bigint,
       1 + (random() * 4)::int,
       round((random() * 500 + 1)::numeric, 2),
       o.placed_at
FROM orders o, generate_series(1, :items_per_order);

ANALYZE;
